In [3]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

## **Import data**

In [11]:
data_path=r'C:\AnalyticsProjects\ecommerce-transactions-insights\00_data\01_raw'
customers=pd.read_excel(data_path+'/'+'CustomersData.xlsx')
discount_coupons=pd.read_csv(data_path+'/'+'Discount_Coupon.csv')
orders=pd.read_csv(data_path+'/'+'Online_Sales.csv')
taxes=pd.read_excel(data_path+'/'+'Tax_amount.xlsx')

In [12]:
customers

      CustomerID Gender    Location  Tenure_Months
0          17850      M     Chicago             12
1          13047      M  California             43
2          12583      M     Chicago             33
3          13748      F  California             30
4          15100      M  California             49
...          ...    ...         ...            ...
1463       14438      F    New York             41
1464       12956      F     Chicago             48
1465       15781      M  New Jersey             19
1466       14410      F    New York             45
1467       14600      F  California              7

[1468 rows x 4 columns]

In [14]:
discount_coupons.head()

  Month Product_Category Coupon_Code  Discount_pct
0   Jan          Apparel      SALE10            10
1   Feb          Apparel      SALE20            20
2   Mar          Apparel      SALE30            30
3   Jan         Nest-USA      ELEC10            10
4   Feb         Nest-USA      ELEC20            20

In [15]:
orders.head()

,CustomerID,Transaction_ID,Transaction_Date,Product_SKU,Product_Description,Product_Category,Quantity,Avg_Price,Delivery_Charges,Coupon_Status
0,17850,16679,1/1/2019,GGOENEBJ079499,Nest Learning Thermostat 3rd Gen-USA - Stainle...,Nest-USA,1,153.71,6.5,Used
1,17850,16680,1/1/2019,GGOENEBJ079499,Nest Learning Thermostat 3rd Gen-USA - Stainle...,Nest-USA,1,153.71,6.5,Used
2,17850,16681,1/1/2019,GGOEGFKQ020399,Google Laptop and Cell Phone Stickers,Office,1,2.05,6.5,Used
3,17850,16682,1/1/2019,GGOEGAAB010516,Google Men's 100% Cotton Short Sleeve Hero Tee...,Apparel,5,17.53,6.5,Not Used
4,17850,16682,1/1/2019,GGOEGBJL013999,Google Canvas Tote Natural/Navy,Bags,1,16.50,6.5,Used

In [16]:
taxes.head()

  Product_Category   GST
0         Nest-USA  0.10
1           Office  0.10
2          Apparel  0.18
3             Bags  0.18
4        Drinkware  0.18

In [17]:
orders.Coupon_Status.value_counts()

Coupon_Status
Clicked     26926
Used        17904
Not Used     8094
Name: count, dtype: int64